"""add_model_registry

Revision ID: 7f5651955ace
Revises: b1737149c186
Create Date: 2026-09-20 19:48:37.720027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5651955ace'
down_revision: Union[str, Sequence[str], None] = 'b1737149c186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('blood_group', sa.String(length=8), nullable=True),
    sa.Column('component', sa.String(length=32), nullable=True),
    sa.Column('artifact_path', sa.String(length=512), nullable=False),
    sa.Column('training_points', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_facility_id'), 'model_registry', ['facility_id'], unique=False)
    op.create_index(op.f('ix_model_registry_name'), 'model_registry', ['name'], unique=False)
    op.create_index(op.f('ix_model_registry_organization_id'), 'model_registry', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_registry_organization_id'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_name'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_facility_id'), table_name='model_registry')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
