"""Initial schema

Revision ID: b1737149c186
Revises: 
Create Date: 2026-09-18 22:36:47.598943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1737149c186'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('HOSPITAL_NETWORK', 'BLOOD_BANK', 'REGIONAL_CENTER', name='organizationtype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('facilities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('facility_type', sa.Enum('HOSPITAL', 'BLOOD_BANK', 'REGIONAL_CENTER', name='facilitytype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('operating_status', sa.Enum('OPERATIONAL', 'DEGRADED', 'OFFLINE', name='operatingstatus'), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'ORG_ADMIN', 'BLOOD_BANK_MANAGER', 'HOSPITAL_MANAGER', 'LOGISTICS_COORDINATOR', 'ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('inventory_units',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('blood_group', sa.Enum('O_POS', 'O_NEG', 'A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', name='bloodgroup'), nullable=False),
    sa.Column('component', sa.Enum('WHOLE_BLOOD', 'RBC', 'PLASMA', 'PLATELETS', 'CRYOPRECIPITATE', name='bloodcomponent'), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'IN_TRANSIT', 'USED', 'EXPIRED', 'DISCARDED', name='unitstatus'), nullable=False),
    sa.Column('storage_location', sa.String(), nullable=True),
    sa.Column('quantity_ml', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_units_expiration_date'), 'inventory_units', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_inventory_units_status'), 'inventory_units', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_units_status'), table_name='inventory_units')
    op.drop_index(op.f('ix_inventory_units_expiration_date'), table_name='inventory_units')
    op.drop_table('inventory_units')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
